---
#Ansible role for installing windows packages using Chocolatey
- name: Install package using Chocolatey
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install package
      win_chocolatey:
        name: "{{ BW_WINDOWS_PACKAGE }}"
        state: {{ BW_WINDOWS_STATE | default('present') }}
        when: BW_WINDOWS_PACKAGE is defined